<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="**\*.axaml">
            <SubType>Designer</SubType>
        </AvaloniaResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.8" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.8" />
    </ItemGroup>
</Project>
